# Deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-users-deployment
  labels:
    app: ms-users
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-users
  template:
    metadata:
      labels:
        app: ms-users
    spec:
      containers:
      - name: ms-users
        image: ms_users_image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
---
# Service file

apiVersion: v1
kind: Service
metadata:
  name: ms-users-service
spec:
  # Décommenter la ligne suivante pour fonctionner en local
  # type: LoadBalancer
  selector:
    app: ms-users
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # Décommenter la ligne suivante pour fonctionner en local
      #nodePort: 30000