# Deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-irttrackings-deployment
  labels:
    app: ms-irttrackings
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-irttrackings
  template:
    metadata:
      labels:
        app: ms-irttrackings
    spec:
      containers:
        - name: ms-irttrackings
          image: ms_irttrackings_image
          imagePullPolicy: Never
          ports:
            - containerPort: 3003
---
# Service file

apiVersion: v1
kind: Service
metadata:
  name: ms-irttrackings-service
spec:
  # Décommenter la ligne suivante pour fonctionner en local
  # type: LoadBalancer
  selector:
    app: ms-irttrackings
  ports:
    - protocol: TCP
      port: 3003
      targetPort: 3003
      # Décommenter la ligne suivante pour fonctionner en local
      # nodePort: 30003
