# Deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-commands-deployment
  labels:
    app: ms-commands
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-commands
  template:
    metadata:
      labels:
        app: ms-commands
    spec:
      containers:
        - name: ms-commands
          image: ms_commands_image
          imagePullPolicy: Never
          ports:
            - containerPort: 3001
---
# Service file

apiVersion: v1
kind: Service
metadata:
  name: ms-commands-service
spec:
  # Décommenter la ligne suivante pour fonctionner en local
  # type: LoadBalancer
  selector:
    app: ms-commands
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      # Décommenter la ligne suivante pour fonctionner en local
      # nodePort: 30001
