apiVersion: v1
kind: Service
metadata:
    name: "ubervegan-908a"
    labels:
        app: "ubervegan-908a"
spec:
    type: LoadBalancer
    ports:
    - port: 3001
      targetPort: 3001
      protocol: TCP
      name: http
    selector:
        app: "ubervegan-908a"