# Deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: notification_image
          imagePullPolicy: Never
          ports:
            - containerPort: 3005
---
# Service file

apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  # Décommenter la ligne suivante pour fonctionner en local
  type: LoadBalancer
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 3005
      targetPort: 3005
      # Décommenter la ligne suivante pour fonctionner en local
      nodePort: 30005
