# Deployment file

apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deployment
  labels:
    app: gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: gateway
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
        - name: gateway
          image: gateway_image
          imagePullPolicy: Never
          ports:
            - containerPort: 3000
---
# Service file

apiVersion: v1
kind: Service
metadata:
  name: gateway-service
spec:
  # Décommenter la ligne suivante pour fonctionner en local
  type: LoadBalancer
  selector:
    app: gateway
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      # Décommenter la ligne suivante pour fonctionner en local
      nodePort: 30000
